/* TASKS */
export const GET_MEMBERS = "GET_MEMBERS"

export const ADD_MEMBER = "ADD_MEMBER"
export const UPDATE_MEMBER = "UPDATE_MEMBER"
export const DELETE_MEMBER = "DELETE_MEMBER"


export const GET_MEMBER_SUCCESSFUL = "GET_MEMBER_SUCCESSFUL"
export const GET_MEMBER_FAILED = "GET_MEMBER_FAILED"

export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS"
export const ADD_MEMBER_FAIL = "ADD_MEMBER_FAIL"

export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS"
export const UPDATE_MEMBER_FAIL = "UPDATE_MEMBER_FAIL"

export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS"
export const DELETE_MEMBER_FAIL = "DELETE_MEMBER_FAIL"