export const GET_MEMBERS = "GET_MEMBERS"
export const GET_MEMBER_SUCCESSFUL = "GET_MEMBER_SUCCESSFUL"
export const GET_MEMBER_FAILED = "GET_MEMBER_FAILED"


export const UPDATE_MEMBERS = "UPDATE_MEMBERS"
export const UPDATE_MEMBER_SUCCESSFUL = "UPDATE_MEMBER_SUCCESSFUL"
export const UPDATE_MEMBER_FAILED = "UPDATE_MEMBER_FAILED"


export const DELETE_MEMBERS = "DELETE_MEMBERS"
export const DELETE_MEMBER_SUCCESSFUL = "DELETE_MEMBER_SUCCESSFUL"
export const DELETE_MEMBER_FAILED = "DELETE_MEMBER_FAILED"
