/* TASKS */
export const GET_WEBSITES = "GET_WEBSITES"
export const GET_WEBSITE_SUCCESS = "GET_WEBSITE_SUCCESS"
export const GET_WEBSITE_FAIL = "GET_WEBSITE_FAIL"

export const ADD_NEW_WEBSITE = "ADD_NEW_WEBSITE"
export const UPDATE_WEBSITE = "UPDATE_WEBSITE"
export const DELETE_WEBSITE = "DELETE_WEBSITE"



export const ADD_WEBSITE_SUCCESS = "ADD_WEBSITE_SUCCESS"
export const ADD_WEBSITE_FAIL = "ADD_WEBSITE_FAIL"
export const UPDATE_WEBSITE_SUCCESS = "UPDATE_WEBSITE_SUCCESS"
export const UPDATE_WEBSITE_FAIL = "UPDATE_WEBSITE_FAIL"
export const DELETE_WEBSITE_SUCCESS = "DELETE_WEBSITE_SUCCESS"
export const DELETE_WEBSITE_FAIL = "DELETE_WEBSITE_FAIL"